apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: angular-index-html-role
rules:
- apiGroups: ["", "batch", "v1", "apps"]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: angular-index-html-role-binding
 namespace: dev
roleRef:
 kind: Role
 name: angular-index-html-role
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: angular-index-html-sa
  namespace: dev

---

apiVersion: v1
kind: ServiceAccount
metadata:
 name: angular-index-html-sa
 namespace: dev
